### ISSUE TITLE
studio-ui自行编译启动会报错

### ISSUE THREAD

**Issue by jiangquan95** [hugegraph/hugegraph-studio#12]
1. 下载sudio-ui代码，yarn install依赖
2. 执行yarn run start 命令，打开浏览器，发现如下错误
![image](https://user-images.githubusercontent.com/11548301/50957465-434c5900-14f9-11e9-82ea-dc645f667ef5.png)
3. 能否给出使用vscode的launch.json配置

**Comment by Linary** [comment]
studio一直是使用npm编译和部署的，你用 npm 试试。
