### ISSUE TITLE
如何本地运行 studio

### ISSUE THREAD

**Issue by dengziming** [hugegraph/hugegraph-studio#13]
我想 debug 一下代码，然后修改某些源码适配我们的业务，但是在 IDEA 启动 `com.baidu.hugegraph.studio.HugeGraphStudio` 类，但是 studio-dist 模块并没有依赖 studio-api 模块，所以找不到 studio-api 中的依赖，想问一下开发者怎么在本地运行测试的。谢谢

**Comment by chentianlong1993** [comment]
@dengziming 你好 问题解决了吗 我也遇到本地无法调试的问题

**Comment by Linary** [comment]
@dengziming studio不好直接在IDEA里进行调试。你可以将studio打包，用命令行启动，启动时增加 -debug 参数，然后在IDEA中使用远程调试的方式，连接端口为8414。
