### ISSUE TITLE
需求：支持PLAIN SASL (username/password)

### ISSUE THREAD

**Issue by yangbh** [hugegraph/hugegraph-studio#14]
可以支持tinkerpop的PLAIN SASL吗？
http://tinkerpop.apache.org/docs/current/reference/#Security
![image](https://user-images.githubusercontent.com/7778764/53626832-bc3a7800-3c41-11e9-8217-4bef22f4d257.png)

**Comment by javeme** [comment]
@yangbh studio可以支持权限认证的，不过hugegraph-server目前只支持HTTP Basic方式，所以studio使用Basic方式会比较好与server兼容。后续我们会排期加入该功能，请确认如下使用流程是否可接受？
```
1. hugegraph-server服务端启用认证，并配置相关图的user:token。
2. hugegraph-studio配置启用认证，可选择页面输入user:token方式认证，
   或者使用studio配置文件写死user:token方式认证。
```

附：[hugegraph-server服务端启用权限认证](https://hugegraph.github.io/hugegraph-doc/config/config-authentication.html)

**Comment by javeme** [comment]
相关issues：
- hugegraph-studio后期考虑加入administration机制吗？
   https://github.com/hugegraph/hugegraph/issues/31
- hugegraph authentication怎么配置和使用,使用默认配置在启动server时超时
   https://github.com/hugegraph/hugegraph/issues/125
- 请问单个图如果解决权限问题
   https://github.com/hugegraph/hugegraph/issues/187

**Comment by yangbh** [comment]
@javeme 多谢多谢，没发现这个功能
