### ISSUE TITLE
请问如何本地运行studio

### ISSUE THREAD

**Issue by xiuxiuing** [hugegraph/hugegraph-studio#15]
我想本地debug studio，请问怎么运行呢

**Comment by javeme** [comment]
@xiuxiuing Java端与普通程序调试差异不大，需要根据你使用的IDE而定，可以搜索一下比如“eclipse tomcat debug”。JS端可以在浏览器中调试。

**Comment by chentianlong1993** [comment]
@javeme Java端本地启动报"Error creating bean with name 'boardSerializer' defined in file xxx",源码下载后没有改过任何配置，为何会报spring创建bean失败呢？
另外，前端npm install也会报错，应该如何调试呢？
