### ISSUE TITLE
查询失败

### ISSUE THREAD

**Issue by mikeguohz** [hugegraph/hugegraph-studio#18]
![image](https://user-images.githubusercontent.com/49983146/56733047-9fc64200-6791-11e9-9704-976aa6cd1ca2.png)

**Comment by javeme** [comment]
@mikeguohz 请详细描述一下出现的场景和复现过程，以方便分析解决。

**Comment by xumanhua** [comment]
同样出现以上问题，安装好服务后安装studio（包括编译和直接下载二进制都试过），然后在界面查询，点击查询就出现网页这个错误

**Comment by xumanhua** [comment]
@javeme

**Comment by javeme** [comment]
@xumanhua 请问是0.9版本的吗？能否提供一下运行机器的环境信息

**Comment by xumanhua** [comment]
是的。0.9.0，需要哪些环境信息，x86_64 x86_64 x86_64 GNU/Linux ，gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)，
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
@javeme

**Comment by hgp2012** [comment]
![image](https://user-images.githubusercontent.com/24802883/56860523-0e8de000-69ca-11e9-9d47-e37a27d9be7d.png)
同样的问题

**Comment by Noodlescn** [comment]
me too

**Comment by Noodlescn** [comment]
![image](https://user-images.githubusercontent.com/20685225/56954360-2fdd0080-6b71-11e9-8f02-43e65731ffeb.png)

**Comment by javeme** [comment]
@all 看起来是个Bug，我们正在尝试复现与分析该问题，会尽快解决的。

**Comment by cmdares** [comment]
关注！
期待官方抓紧分析和修复，正准备在应用环境中试用0.9的版本。
感谢！

**Comment by Linary** [comment]
@cmdares 抱歉，这的确是一个BUG，最新的 release-0.9.0 已修复，请知晓。
