### ISSUE TITLE
hi, 有hugegraph的0.7.4编译版吗?

### ISSUE THREAD

**Issue by lijin007** [hugegraph/hugegraph-studio#2]
我这儿无法编译成功, 编译版的下载地址在哪儿?
![default](https://user-images.githubusercontent.com/5925394/45734140-f248ea00-bc15-11e8-9b19-1d280a22b0e9.png)

**Comment by Linary** [comment]
你这个的问题应该是studio版本（0.6）低于server（0.7），你应该去下载较新的studio

下载地址：https://github.com/hugegraph/hugegraph-studio/releases/download/v0.7.0/hugegraph-studio-0.7.0.tar.gz
