### ISSUE TITLE
long 型 id 精度丢失

### ISSUE THREAD

**Issue by LayGit** [hugegraph/hugegraph-studio#27]
后端返回前端的时候，针对 Long 类型要处理一下，转成 String 再返给前端，不然会丢失精度。

**Comment by javeme** [comment]
@LayGit 没有太明白具体丢失情况？是否可以更加详细的描述一下呢？

**Comment by LayGit** [comment]
比如一个 Long 型的 id 是 `61695499031416832` ，Studio 网页上显示的是 `61695499031416830`

**Comment by javeme** [comment]
@LayGit 好的多谢反馈，由于我这边使用61695499031416832作为CUSTOMIZE_NUMBER顶点的id，查出来的结果没有精度丢失。是否能提供一下复现的流程，另外后端存储使用的是什么？

**Comment by LayGit** [comment]
后端用的 Java Client SDK 操作的，实际的精度是没有问题的，只是 Studio 是 js 处理的这个超长 id 所以存在问题，可以看看：[https://blog.csdn.net/u010028869/article/details/86563382](https://blog.csdn.net/u010028869/article/details/86563382)
查询：
`g.V(65123051355901952)`

返回：
`{"id":"77ce8ae7-01b9-4120-81b7-d594f4057005","data":[{"id":65123051355901952,"label":"user","type":"vertex","properties":{"userVipLevel":3}}],"type":"VERTEX","duration":209,"showNum":1,"message":"","graph":{"vertices":[{"label":"user","type":"vertex","properties":{"userVipLevel":3},"id":65123051355901952}],"edges":[],"styles":{"groups":{"user":{"shape":"dot","size":25,"color":{"background":"#ED5736","border":"#ED5736","highlight":{"border":"#ED5736","background":"#ED5736"},"hover":{"border":"#312520","background":"#312520"}},"icon":{"face":"FontAwesome","code":"","size":50,"color":"#2B7CE9"},"scaling":{"min":25,"max":30}}},"font":{"color":"#343434","size":12,"face":"arial","multi":false},"edgeColor":{"color":"#A0A0A0","highlight":"#606060","hover":"#808080"},"edgeFont":{"color":"#77777","size":11,"face":"arial","multi":false}}}}`

返回的JSON中的 Long 型数值没有处理，导致精度丢失

**Comment by Linary** [comment]
@LayGit 感谢反馈，我们会尽快修复此问题

**Comment by Linary** [comment]
问题已在 #30 中修复
