### ISSUE TITLE
hugegraph-studio一开始是支持连接多个图,并且可以显示schema信息的,后来更新成只能连接一个指定的图,为什么做了这样的修改,之前那个版本有问题吗

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph-studio#3]

**Comment by javeme** [comment]
@fisherinbox 感谢反馈。是的，由于之前的版本存在一些技术及非技术的问题，所以对功能做了简化，并计划调整studio的整个技术框架，新的版本在稳定性上有了提升。后续我们会持续增加更多功能到studio，以提供更加简单的使用方式。
