### ISSUE TITLE
Error! Could not rebind [g] to [__g_hugegraph] as [__g_hugegraph] not in the Graph or TraversalSource global bindings

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph-studio#36]
HugeGraph-Serve: version 0.10.4
HugeGraph-Studio: version 0.10.0
After successfully  launched HugeGraph-Serve and HugeGraph-Studio, I could use restful API to visit the graph, but when I ran `g.V()` in the HugeGraph-Studio Browser, I got error:
> Error!
> Could not rebind [g] to [__g_hugegraph] as [__g_hugegraph] not in the Graph or TraversalSource global bindings

**Comment by javeme** [comment]
@chencjiajy 请检查一下hugegraph-server是否启动成功了，错误日志中是否有错误

**Comment by chencjiajy** [comment]
hugegraph-server成功启动了，并且可以使用curl 进行图查询

**Comment by suesunss** [comment]
@chencjiajy 

这个可能因为 server 配置的图名和 studio 连接的图名不一致导致。可以查看下 server `conf` 目录下配置的图和 `hugegraph-studio.properties` 中连接的图是否一致。

**Comment by chencjiajy** [comment]
@suesunss 谢谢，很可能是这个原因，我当时改过gremlin-server.yaml和rest-server.properties中的图名，不过我当时测的环境不在了，没法验证
