### ISSUE TITLE
建议在文档中注明对npm对依赖

### ISSUE THREAD

**Issue by n0b0dyCN** [hugegraph/hugegraph-studio#4]
建议在文档中注明对npm对依赖：
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
sudo apt install -y nodejs
sudo apt install autoconf automake libtool libpng-dev
```
否则在编译的时候会报错。

**Comment by javeme** [comment]
@n0b0dyCN 好的我们会尽快完善到文档中，多谢反馈。

**Comment by 0xAlbertChen** [comment]
其他版本Linux系统
https://github.com/nodesource/distributions#rpminstall

**Comment by 0xAlbertChen** [comment]
网络有问题装不上可以参考
https://linuxize.com/post/how-to-install-node-js-on-centos-7/#1-install-nvm-node-version-manager

**Comment by 0xAlbertChen** [comment]
我投降了
```
  [exec]
     [exec] > pngquant-bin@4.0.0 postinstall /root/hugeGraph/hugegraph-studio/studio-ui/node_modules/pngquant-bin
     [exec] > node lib/install.js
     [exec]
     [exec]   ⚠ The `/root/hugeGraph/hugegraph-studio/studio-ui/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
     [exec]   ⚠ pngquant pre-build test failed
     [exec]   ℹ compiling from source
     [exec]   ✔ pngquant pre-build test passed successfully
     [exec]   ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
     [exec]     at Promise.all.then.arr (/root/hugeGraph/hugegraph-studio/studio-ui/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
     [exec]     at process.internalTickCallback (internal/process/next_tick.js:77:7)
     [exec] npm WARN web@1.0.0 No description
     [exec] npm WARN web@1.0.0 No repository field.
     [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
     [exec] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
     [exec]
     [exec] npm ERR! code ELIFECYCLE
     [exec] npm ERR! errno 1
     [exec] npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
     [exec] npm ERR! Exit status 1
     [exec] npm ERR!
     [exec] npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
     [exec] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
     [exec]
     [exec] npm ERR! A complete log of this run can be found in:
     [exec] npm ERR!     /root/.npm/_logs/2018-11-27T07_52_27_464Z-debug.log
```

**Comment by n0b0dyCN** [comment]
> 我投降了
> 
> ```
>   [exec]
>      [exec] > pngquant-bin@4.0.0 postinstall /root/hugeGraph/hugegraph-studio/studio-ui/node_modules/pngquant-bin
>      [exec] > node lib/install.js
>      [exec]
>      [exec]   ⚠ The `/root/hugeGraph/hugegraph-studio/studio-ui/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
>      [exec]   ⚠ pngquant pre-build test failed
>      [exec]   ℹ compiling from source
>      [exec]   ✔ pngquant pre-build test passed successfully
>      [exec]   ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
>      [exec]     at Promise.all.then.arr (/root/hugeGraph/hugegraph-studio/studio-ui/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
>      [exec]     at process.internalTickCallback (internal/process/next_tick.js:77:7)
>      [exec] npm WARN web@1.0.0 No description
>      [exec] npm WARN web@1.0.0 No repository field.
>      [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
>      [exec] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
>      [exec]
>      [exec] npm ERR! code ELIFECYCLE
>      [exec] npm ERR! errno 1
>      [exec] npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
>      [exec] npm ERR! Exit status 1
>      [exec] npm ERR!
>      [exec] npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
>      [exec] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>      [exec]
>      [exec] npm ERR! A complete log of this run can be found in:
>      [exec] npm ERR!     /root/.npm/_logs/2018-11-27T07_52_27_464Z-debug.log
> ```

You may trying this:
```
sudo apt install libpng-dev
```

**Comment by n0b0dyCN** [comment]
> 我投降了
> 
> ```
>   [exec]
>      [exec] > pngquant-bin@4.0.0 postinstall /root/hugeGraph/hugegraph-studio/studio-ui/node_modules/pngquant-bin
>      [exec] > node lib/install.js
>      [exec]
>      [exec]   ⚠ The `/root/hugeGraph/hugegraph-studio/studio-ui/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
>      [exec]   ⚠ pngquant pre-build test failed
>      [exec]   ℹ compiling from source
>      [exec]   ✔ pngquant pre-build test passed successfully
>      [exec]   ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
>      [exec]     at Promise.all.then.arr (/root/hugeGraph/hugegraph-studio/studio-ui/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
>      [exec]     at process.internalTickCallback (internal/process/next_tick.js:77:7)
>      [exec] npm WARN web@1.0.0 No description
>      [exec] npm WARN web@1.0.0 No repository field.
>      [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
>      [exec] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
>      [exec]
>      [exec] npm ERR! code ELIFECYCLE
>      [exec] npm ERR! errno 1
>      [exec] npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
>      [exec] npm ERR! Exit status 1
>      [exec] npm ERR!
>      [exec] npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
>      [exec] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>      [exec]
>      [exec] npm ERR! A complete log of this run can be found in:
>      [exec] npm ERR!     /root/.npm/_logs/2018-11-27T07_52_27_464Z-debug.log
> ```

试一下安装libpng库
```
sudo apt install libpng-dev
```

**Comment by xy83918** [comment]
`yum install libpng-devel`

**Comment by 0xAlbertChen** [comment]
> 我投降了
> 
> ```
>   [exec]
>      [exec] > pngquant-bin@4.0.0 postinstall /root/hugeGraph/hugegraph-studio/studio-ui/node_modules/pngquant-bin
>      [exec] > node lib/install.js
>      [exec]
>      [exec]   ⚠ The `/root/hugeGraph/hugegraph-studio/studio-ui/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
>      [exec]   ⚠ pngquant pre-build test failed
>      [exec]   ℹ compiling from source
>      [exec]   ✔ pngquant pre-build test passed successfully
>      [exec]   ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
>      [exec]     at Promise.all.then.arr (/root/hugeGraph/hugegraph-studio/studio-ui/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
>      [exec]     at process.internalTickCallback (internal/process/next_tick.js:77:7)
>      [exec] npm WARN web@1.0.0 No description
>      [exec] npm WARN web@1.0.0 No repository field.
>      [exec] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
>      [exec] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
>      [exec]
>      [exec] npm ERR! code ELIFECYCLE
>      [exec] npm ERR! errno 1
>      [exec] npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
>      [exec] npm ERR! Exit status 1
>      [exec] npm ERR!
>      [exec] npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
>      [exec] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>      [exec]
>      [exec] npm ERR! A complete log of this run can be found in:
>      [exec] npm ERR!     /root/.npm/_logs/2018-11-27T07_52_27_464Z-debug.log
> ```
CentOS 7 的安装命令是`yum install libpng-devel`

**Comment by xumanhua** [comment]
编译完成后，只要执行命令就出现下面错误

uncaught Error: ace.edit can't find div #card_default_editor
    at Object.exports.edit (ace.js:18997)
    at QueryCard.__execute__REACT_HOT_LOADER__ (querycard.jsx:152)
    at QueryCard._this.execute (querycard.jsx:46)
    at HTMLUnknownElement.boundFunc (ReactErrorUtils.js:63)
    at Object../node_modules/react-dom/lib/ReactErrorUtils.js.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:69)
    at executeDispatch (EventPluginUtils.js:83)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:106)
    at executeDispatchesAndRelease (EventPluginHub.js:41)
    at executeDispatchesAndReleaseTopLevel (EventPluginHub.js:52)
    at Array.forEach (<anonymous>)

**Comment by scottMan1001** [comment]
所以这个 当我进入stuio-ui层，使用npm install 安装依赖报错的问题，还有解决方法吗？

**Comment by mrdaihui** [comment]
这个是不是对node npm的版本有要求啊，我编译的时候报npm弃用一些包的警告，然后卡住一直不动
![image](https://user-images.githubusercontent.com/37104103/99768588-fa777980-2b3f-11eb-9885-e58adb7fe34b.png)
